baseURL = "http://www.example.com"
title = "akash_mahapatra"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true


[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Akash Mahapatra"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Akash Mahapatra's personal website"
keywords = "blog, solutions architect, enterprise architect, data engineer, aws, azure, gcp, cloud, devops, devsecops, api, api management, data management, kafka"
info = [ "Solutions Architect", "", "Enterprise Integration | Data Management | Cloud-Native DevOps"]
dateFormat = "January 2, 2006"
since = 2019
avatarURL = "images/avatar_akash.jpg"
colorScheme = "light"
hideColorSchemeToggle = true
commit = "https://github.com/Ganitagya/Ganitagya.github.io"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/akash-mahapatra/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/Ganitagya"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/AkashMhptr"

[[params.social]]
name = "Stack Overflow"
icon = "fa-brands fa-stack-overflow fa-2x"
weight = 4
url = "https://stackoverflow.com/users/6544931/akash-mahapatra?tab=profile"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@akash-mhptr"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Solution-Architectures"
weight = 1
url = "Solution-Architecture/"


[[languages.en.menu.main]]
name = "TEXperiments"
weight = 2
url = "TEXperiments/"

[[languages.en.menu.main]]
name = "MahaTechBharat"
weight = 3
url = "MahaTechBharat/"